---
assess:
        file: ZZZ_1_9606.txt 
        #Only One prediction file allowed
        obo: ./precrec/go_cafa3.obo
        benchmark: ./precrec/benchmark/CAFA3_benchmarks/
        results: ./results/
plot:
        results: ./results/
        title: 9606
        smooth: N
        file1: ZZZ_1_9606
        #file2: ZZZ_2_9606
        #file3: XXX_1_9606
        # Above files will be shown on one plot
        # We recommend only plotting results for the same species together
        # You can add up to 12 files
        # title is optional
